ModelChemicalProduction: 0 #Flag to turn on or off Chemical Production modeling - 0 - No Chemicals, 1 - Chemical Production Modeled
# Chemical Prodcution include: Ethylene and ammonia. "Only Ethylene is active for now" 

ModelEthylenePurchase: 0 # Flag to turn on or off Ethylene Purchase modeling
ModelEthyleneProduction: 0 #Flag to turn on or off Ethylene Prodcution modeling
Conventional_Ethylene_Purchase_Share_Requirement: 0 # Specify Conventional Ethylene Purchase Share ; 0 = not active; 1 = active systemwide
Conv_Ethylene_Purchase_Share: 0 # Enter a value between 0 and 1 to specify the maximum fraction of systemwide conventional ethylene purchase




